version: '3.3'

services:
  backend:
    build: ../main/
    # image: beszedin/lenta:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - static_value:/app/staticfiles/
    depends_on:
      - redis
    # environment:
    #   - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    #   - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
  
  nginx_two:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../docs/:/usr/share/nginx/html/api/docs/
      # - static_value:/var/html/staticfiles/
    depends_on:
      - backend
  
  redis:
    image: redis:latest
  
  celery:
    build: ../main/
    command: celery -A main worker -l info
    volumes:
      - ../main/:/app/
    depends_on:
      - backend
      - redis

volumes:
  static_value:
  media_value: