version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    build: ../main/
    restart: always
    ports:
      - "8080:8080"
    # volumes:
    #   - static_value:/app/staticfiles/
    depends_on:
      - db
      - redis
  
  nginx_two:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
  
  redis:
    image: redis:latest
  
  celery:
    build: ../main/
    command: celery -A main worker -l info
    volumes:
      - ../main/:/app/
    depends_on:
      - db
      - backend
      - redis

volumes:
  postgres_data:
