# Generated by Django 4.2.7 on 2023-11-14 09:31

from django.db import migrations, models
import service.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=100, validators=[service.validators.validate_cadastral_number], verbose_name='Кадастровый номер')),
                ('latitude', models.FloatField(validators=[service.validators.validate_latitude], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[service.validators.validate_longitude], verbose_name='Долгота')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('response', models.BooleanField()),
            ],
            options={
                'verbose_name': 'История запросов',
            },
        ),
    ]
