# Generated by Django 4.2.7 on 2023-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='response',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
